books/urls.py
from django.urls import path
from .views import BookListView, AddBookView, EditBookView, BookDetailView, DeleteBookView, BookListViewDRF
from .views import BookDetailView

app_name = 'books'

urlpatterns = [
    path('books/', BookListView.as_view(), name='book_list'),
    path('add/', AddBookView.as_view(), name='add_book'),
    path('edit/<int:pk>/', EditBookView.as_view(), name='book_edit'),
    path('detail/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('delete/<int:pk>/delete/', DeleteBookView.as_view(), name='book_delete'),
    path('books-list/', BookListViewDRF.as_view(), name='book-list'),
    path('book-detail/<int:pk>/', BookDetailView.as_view(), name='book-detail'),
]

openlibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

books/models.py
from django.db import models

# el campo authors debería ser un modelo aparte y establecerse una relación ManyToMany
class Book(models.Model):
    title = models.CharField(max_length=200) #title
    author = models.CharField(max_length=200) #author_name
    isbn = models.CharField(max_length=13) #isbn []
    publication_date = models.DateField() #first_publish_year
    pages = models.PositiveIntegerField() #number_of_pages_median
    cover_image = models.URLField() #cover_i

    def __str__(self):
        return self.title

books/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Book
from django.utils import timezone

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'isbn', 'publication_date', 'pages', 'cover_image']

    def clean_author(self):
        author = self.cleaned_data.get('author')
        if any(char.isdigit() for char in author):
            raise ValidationError('Author name should not contain numbers.')
        return author

    def clean_isbn(self):
        isbn = self.cleaned_data.get('isbn')
        if not isbn.isdigit() or len(isbn) != 13:
            raise ValidationError('ISBN must be exactly 13 digits.')
        return isbn

    def clean_publication_date(self):
        publication_date = self.cleaned_data.get('publication_date')
        if publication_date > timezone.now().date():
            raise ValidationError('Publication date cannot be in the future.')
        return publication_date

    def clean_pages(self):
        pages = self.cleaned_data.get('pages')
        if pages <= 0:
            raise ValidationError('Number of pages must be greater than 0.')
        return pages

books/views.py
import requests
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, DetailView, DeleteView
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from .models import Book
from .forms import BookForm
from rest_framework import generics
from books.serializers import BookSerializer

class BookListView(ListView):
    model = Book
    template_name = 'books/book_list.html'
    context_object_name = 'books'

    def get_queryset(self):
        queryset = super().get_queryset()
        title_query = self.request.GET.get('title')
        author_query = self.request.GET.get('author')

        if title_query:
            queryset = queryset.filter(title__icontains=title_query)
        if author_query:
            queryset = queryset.filter(author__icontains=author_query)
            
        return queryset
    
class BookListViewDRF(generics.ListCreateAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

class BookDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

class AddBookView(CreateView):
    model = Book
    form_class = BookForm
    template_name = 'books/add_book.html'
    success_url = reverse_lazy('books:book_list')

class EditBookView(UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'books/edit_book.html'
    success_url = reverse_lazy('books:book_list')

    def get_object(self, queryset=None):
        # Obtiene el objeto Book basado en el ID de la URL
        return Book.objects.get(pk=self.kwargs['pk'])
    
class BookDetailView(DetailView):
    model = Book
    template_name = 'books/book_detail.html'
    context_object_name = 'book'

    def get_object(self, queryset=None):
        # Obtiene el objeto Book basado en el ID de la URL
        return Book.objects.get(pk=self.kwargs['pk'])
    
class DeleteBookView(DeleteView):
    model = Book
    template_name = 'books/book_confirm_delete.html'
    success_url = reverse_lazy('books:book_list')

books/templates/books/add_book.html
{% extends './base.html' %}

{% load form_tags %}

{% block title %}Add New Book{% endblock %}

{% block content %}
    <h1 class="mb-4">Add New Book</h1>
    <form method="post" action="{% url 'books:add_book' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title</label>
            {{ form.title|add_class:"form-control" }}
            {% if form.title.errors %}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_author">Author</label>
            {{ form.author|add_class:"form-control" }}
            {% if form.author.errors %}
                <div class="invalid-feedback">
                    {% for error in form.author.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_isbn">ISBN</label>
            {{ form.isbn|add_class:"form-control" }}
            {% if form.isbn.errors %}
                <div class="invalid-feedback">
                    {% for error in form.isbn.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_publication_date">Publication Date</label>
            {% comment %} {{ form.publication_date|add_class:"form-control" }} {% endcomment %}
            <input type="date" name="publication_date" id="id_publication_date" class="form-control" required>
            {% if form.publication_date.errors %}
                <div class="invalid-feedback">
                    {% for error in form.publication_date.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_pages">Number of Pages</label>
            {{ form.pages|add_class:"form-control" }}
            {% if form.pages.errors %}
                <div class="invalid-feedback">
                    {% for error in form.pages.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_cover_image">Cover Image URL</label>
            {{ form.cover_image|add_class:"form-control" }}
            {% if form.cover_image.errors %}
                <div class="invalid-feedback">
                    {% for error in form.cover_image.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Add Book</button>
        <a href="{% url 'books:book_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

books/templates/books/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Book App{% endblock %}</title>
    <!-- Bootstrap CSS (usando CDN para simplicidad) -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Font Awesome CSS (para los íconos) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <div class="container mt-5">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Bootstrap JS and dependencies (usando CDN) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

books/templates/books/book_confirm_delete.html
{% extends './base.html' %}

{% load form_tags %}

{% block title %}Edit Book{% endblock %}

{% block content %}
    <h1>Are you sure you want to delete "{{ book.title }}"?</h1>
    <form method="post">{% csrf_token %}
        <button type="submit" class="btn btn-primary">Confirm</button>
        <button type="button" class="btn btn-secondary" onclick="history.back()">Cancel</button>
    </form>
{% endblock %}

books/templates/books/book_detail.html
{% extends './base.html' %}

{% load form_tags %}

{% block title %}Edit Book{% endblock %}

{% block content %}
    <!-- Información del libro -->
    <div class="book-info">
        <h1>Title: {{ book.title }}</h1>
        <p>Author: {{ book.author }}</p>
        <p>Published Date: {{ book.published_date|date:"d/m/Y" }}</p>
        
        <!-- Mostrar la imagen de portada si existe -->
        {% if book.cover_image %}
            <p>Cover Image:</p>
            <img src="{{ book.cover_image }}" alt="Cover Image" style="width: 150px; height: auto;">
        {% else %}
            <p>No Cover Image Available</p>
        {% endif %}
        
        <!-- Añade más campos según sea necesario -->
    </div>
    
    <!-- Contenedor para los botones -->
    <div class="button-group mt-4">
        <a href="{% url 'books:book_list' %}" class="btn btn-secondary">Book List</a>
        <a href="{% url 'books:book_edit' book.pk %}" class="btn btn-primary">Edit</a>
    </div>
    
    <div class="button-group mt-2">
        <button class="btn btn-danger btn" onclick="if(confirm('Are you sure you want to delete this book?')) { window.location.href='{% url 'books:book_delete' book.pk %}'; }">Delete</button>
    </div>
{% endblock %}

books/templates/books/book_list.html
<!-- templates/books/book_list.html -->
{% extends './base.html' %}

{% block title %}Book List{% endblock %}

{% block content %}    
    <form method="GET" class="d-flex mb-4">
        <div class="form-group mr-2">
            <input type="text" name="title" class="form-control" placeholder="Search by Title" value="{{ request.GET.title }}">
        </div>
        <div class="form-group mr-2">
            <input type="text" name="author" class="form-control" placeholder="Search by Author" value="{{ request.GET.author }}">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </form>
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Book List</h1>
        <a href="{% url 'books:add_book' %}" class="btn btn-primary">Add New Book</a>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Title</th>
                <th>Author(s)</th>
                <th>ISBN</th>
                <th>Publication Date</th>
                <th>Number of Pages</th>
                <th>Cover</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.isbn }}</td>
                <td>{{ book.publication_date }}</td>
                <td>{{ book.pages }}</td>
                <td>
                    {% if book.cover_image %}
                    <img src="{{ book.cover_image }}" alt="Cover Image" style="width: 100px; height: auto;">
                    {% else %}
                    No Image
                    {% endif %}
                </td>
                <td class="actions-column" style="display: flex; flex-direction: column; gap: 0.2rem;">
                    <a href="{% url 'books:book_detail' book.id %}" class="btn btn-info btn-sm" title="View Detail">
                        <i class="fas fa-eye"></i>
                    </a>
                    <a href="{% url 'books:book_edit' book.id %}" class="btn btn-warning btn-sm" title="Edit">
                        <i class="fas fa-edit"></i>
                    </a>
                    <button class="btn btn-danger btn-sm" onclick="if(confirm('Are you sure you want to delete this book?')) { window.location.href='{% url 'books:book_delete' book.pk %}'; }">
                        <i class="fas fa-trash"></i>
                    </button>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="8">No books found</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

books/templates/books/edit_book.html
{% extends './base.html' %}

{% load form_tags %}

{% block title %}Edit Book{% endblock %}

{% block content %}
    <h1 class="mb-4">Edit Book</h1>
    <form method="post" action="{% url 'books:book_edit' book.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save Changes</button>
            <a href="{% url 'books:book_list' %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
{% endblock %}

books/templates/error.html
<!-- templates/error.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Something went wrong</h1>
    <p>An unexpected error occurred. Please try again later.</p>
</body>
</html>